<?php


/**
 * This class defines the structure of the 'iog_newsletter_content' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Dec 31 17:14:25 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogNewsletterPlugin.lib.model.map
 */
class iogNewsletterContentTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogNewsletterPlugin.lib.model.map.iogNewsletterContentTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('iog_newsletter_content');
		$this->setPhpName('iogNewsletterContent');
		$this->setClassname('iogNewsletterContent');
		$this->setPackage('plugins.iogNewsletterPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('NEWSLETTER_ID', 'NewsletterId', 'INTEGER', 'iog_newsletter', 'ID', true, null, null);
		$this->addColumn('APARTAT', 'Apartat', 'VARCHAR', false, 255, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 255, null);
		$this->addColumn('SLUG', 'Slug', 'VARCHAR', false, 255, null);
		$this->addColumn('EMAIL_CONTENT', 'EmailContent', 'LONGVARCHAR', false, null, null);
		$this->addColumn('WEB_CONTENT', 'WebContent', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('iogNewsletter', 'iogNewsletter', RelationMap::MANY_TO_ONE, array('newsletter_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // iogNewsletterContentTableMap
