<?php


/**
 * This class defines the structure of the 'iog_newsletter_image' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Dec 31 17:14:26 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogNewsletterPlugin.lib.model.map
 */
class iogNewsletterImageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogNewsletterPlugin.lib.model.map.iogNewsletterImageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('iog_newsletter_image');
		$this->setPhpName('iogNewsletterImage');
		$this->setClassname('iogNewsletterImage');
		$this->setPackage('plugins.iogNewsletterPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('TAG', 'Tag', 'VARCHAR', false, 50, null);
		$this->addForeignKey('IOG_NEWSLETTER_ID', 'IogNewsletterId', 'INTEGER', 'iog_newsletter', 'ID', false, null, null);
		$this->addForeignKey('SF_ASSET_ID', 'SfAssetId', 'INTEGER', 'sf_asset', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('iogNewsletter', 'iogNewsletter', RelationMap::MANY_TO_ONE, array('iog_newsletter_id' => 'id', ), null, null);
    $this->addRelation('sfAsset', 'sfAsset', RelationMap::MANY_TO_ONE, array('sf_asset_id' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // iogNewsletterImageTableMap
