<?php


/**
 * This class defines the structure of the 'iog_newsletter' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Dec 31 17:14:24 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogNewsletterPlugin.lib.model.map
 */
class iogNewsletterTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogNewsletterPlugin.lib.model.map.iogNewsletterTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('iog_newsletter');
		$this->setPhpName('iogNewsletter');
		$this->setClassname('iogNewsletter');
		$this->setPackage('plugins.iogNewsletterPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NUMERO', 'Numero', 'INTEGER', false, null, null);
		$this->addColumn('DATA_PUBLICACIO', 'DataPublicacio', 'TIMESTAMP', false, null, null);
		$this->addColumn('TITULAR', 'Titular', 'VARCHAR', false, 255, null);
		$this->addForeignKey('TEMPLATE_ID', 'TemplateId', 'INTEGER', 'iog_newsletter_template', 'ID', true, null, null);
		$this->addColumn('SEND_DATE', 'SendDate', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('IOG_NEWSLETTER_LLISTA_ID', 'IogNewsletterLlistaId', 'INTEGER', 'iog_newsletter_llista', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('IogNewsletterTemplate', 'IogNewsletterTemplate', RelationMap::MANY_TO_ONE, array('template_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('IogNewsletterLlista', 'IogNewsletterLlista', RelationMap::MANY_TO_ONE, array('iog_newsletter_llista_id' => 'id', ), null, null);
    $this->addRelation('iogNewsletterContent', 'iogNewsletterContent', RelationMap::ONE_TO_MANY, array('id' => 'newsletter_id', ), 'CASCADE', null);
    $this->addRelation('iogNewsletterImage', 'iogNewsletterImage', RelationMap::ONE_TO_MANY, array('id' => 'iog_newsletter_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // iogNewsletterTableMap
