<?php


/**
 * This class adds structure of 'iog_newsletter' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Apr 24 01:12:16 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogNewsletterPlugin.lib.model.map
 */
class iogNewsletterMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogNewsletterPlugin.lib.model.map.iogNewsletterMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(iogNewsletterPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(iogNewsletterPeer::TABLE_NAME);
		$tMap->setPhpName('iogNewsletter');
		$tMap->setClassname('iogNewsletter');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NUMERO', 'Numero', 'INTEGER', false, null);

		$tMap->addColumn('DATA_PUBLICACIO', 'DataPublicacio', 'TIMESTAMP', false, null);

		$tMap->addColumn('TITULAR', 'Titular', 'VARCHAR', false, 255);

	} // doBuild()

} // iogNewsletterMapBuilder
