<?php

/**
 * Base class that represents a row from the 'iog_newsletter' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Dec 31 17:14:24 2010
 *
 * @package    plugins.iogNewsletterPlugin.lib.model.om
 */
abstract class BaseiogNewsletter extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        iogNewsletterPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the numero field.
	 * @var        int
	 */
	protected $numero;

	/**
	 * The value for the data_publicacio field.
	 * @var        string
	 */
	protected $data_publicacio;

	/**
	 * The value for the titular field.
	 * @var        string
	 */
	protected $titular;

	/**
	 * The value for the template_id field.
	 * @var        int
	 */
	protected $template_id;

	/**
	 * The value for the send_date field.
	 * @var        string
	 */
	protected $send_date;

	/**
	 * The value for the iog_newsletter_llista_id field.
	 * @var        int
	 */
	protected $iog_newsletter_llista_id;

	/**
	 * @var        IogNewsletterTemplate
	 */
	protected $aIogNewsletterTemplate;

	/**
	 * @var        IogNewsletterLlista
	 */
	protected $aIogNewsletterLlista;

	/**
	 * @var        array iogNewsletterContent[] Collection to store aggregation of iogNewsletterContent objects.
	 */
	protected $colliogNewsletterContents;

	/**
	 * @var        Criteria The criteria used to select the current contents of colliogNewsletterContents.
	 */
	private $lastiogNewsletterContentCriteria = null;

	/**
	 * @var        array iogNewsletterImage[] Collection to store aggregation of iogNewsletterImage objects.
	 */
	protected $colliogNewsletterImages;

	/**
	 * @var        Criteria The criteria used to select the current contents of colliogNewsletterImages.
	 */
	private $lastiogNewsletterImageCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'iogNewsletterPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [numero] column value.
	 * 
	 * @return     int
	 */
	public function getNumero()
	{
		return $this->numero;
	}

	/**
	 * Get the [optionally formatted] temporal [data_publicacio] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDataPublicacio($format = 'Y-m-d H:i:s')
	{
		if ($this->data_publicacio === null) {
			return null;
		}


		if ($this->data_publicacio === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->data_publicacio);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->data_publicacio, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [titular] column value.
	 * 
	 * @return     string
	 */
	public function getTitular()
	{
		return $this->titular;
	}

	/**
	 * Get the [template_id] column value.
	 * 
	 * @return     int
	 */
	public function getTemplateId()
	{
		return $this->template_id;
	}

	/**
	 * Get the [optionally formatted] temporal [send_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getSendDate($format = 'Y-m-d H:i:s')
	{
		if ($this->send_date === null) {
			return null;
		}


		if ($this->send_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->send_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->send_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [iog_newsletter_llista_id] column value.
	 * 
	 * @return     int
	 */
	public function getIogNewsletterLlistaId()
	{
		return $this->iog_newsletter_llista_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = iogNewsletterPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [numero] column.
	 * 
	 * @param      int $v new value
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setNumero($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->numero !== $v) {
			$this->numero = $v;
			$this->modifiedColumns[] = iogNewsletterPeer::NUMERO;
		}

		return $this;
	} // setNumero()

	/**
	 * Sets the value of [data_publicacio] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setDataPublicacio($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->data_publicacio !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->data_publicacio !== null && $tmpDt = new DateTime($this->data_publicacio)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->data_publicacio = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = iogNewsletterPeer::DATA_PUBLICACIO;
			}
		} // if either are not null

		return $this;
	} // setDataPublicacio()

	/**
	 * Set the value of [titular] column.
	 * 
	 * @param      string $v new value
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setTitular($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titular !== $v) {
			$this->titular = $v;
			$this->modifiedColumns[] = iogNewsletterPeer::TITULAR;
		}

		return $this;
	} // setTitular()

	/**
	 * Set the value of [template_id] column.
	 * 
	 * @param      int $v new value
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setTemplateId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->template_id !== $v) {
			$this->template_id = $v;
			$this->modifiedColumns[] = iogNewsletterPeer::TEMPLATE_ID;
		}

		if ($this->aIogNewsletterTemplate !== null && $this->aIogNewsletterTemplate->getId() !== $v) {
			$this->aIogNewsletterTemplate = null;
		}

		return $this;
	} // setTemplateId()

	/**
	 * Sets the value of [send_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setSendDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->send_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->send_date !== null && $tmpDt = new DateTime($this->send_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->send_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = iogNewsletterPeer::SEND_DATE;
			}
		} // if either are not null

		return $this;
	} // setSendDate()

	/**
	 * Set the value of [iog_newsletter_llista_id] column.
	 * 
	 * @param      int $v new value
	 * @return     iogNewsletter The current object (for fluent API support)
	 */
	public function setIogNewsletterLlistaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->iog_newsletter_llista_id !== $v) {
			$this->iog_newsletter_llista_id = $v;
			$this->modifiedColumns[] = iogNewsletterPeer::IOG_NEWSLETTER_LLISTA_ID;
		}

		if ($this->aIogNewsletterLlista !== null && $this->aIogNewsletterLlista->getId() !== $v) {
			$this->aIogNewsletterLlista = null;
		}

		return $this;
	} // setIogNewsletterLlistaId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->numero = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->data_publicacio = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->titular = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->template_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->send_date = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->iog_newsletter_llista_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = iogNewsletterPeer::NUM_COLUMNS - iogNewsletterPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating iogNewsletter object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aIogNewsletterTemplate !== null && $this->template_id !== $this->aIogNewsletterTemplate->getId()) {
			$this->aIogNewsletterTemplate = null;
		}
		if ($this->aIogNewsletterLlista !== null && $this->iog_newsletter_llista_id !== $this->aIogNewsletterLlista->getId()) {
			$this->aIogNewsletterLlista = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(iogNewsletterPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = iogNewsletterPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aIogNewsletterTemplate = null;
			$this->aIogNewsletterLlista = null;
			$this->colliogNewsletterContents = null;
			$this->lastiogNewsletterContentCriteria = null;

			$this->colliogNewsletterImages = null;
			$this->lastiogNewsletterImageCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(iogNewsletterPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseiogNewsletter:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				iogNewsletterPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseiogNewsletter:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(iogNewsletterPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseiogNewsletter:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseiogNewsletter:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				iogNewsletterPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aIogNewsletterTemplate !== null) {
				if ($this->aIogNewsletterTemplate->isModified() || $this->aIogNewsletterTemplate->isNew()) {
					$affectedRows += $this->aIogNewsletterTemplate->save($con);
				}
				$this->setIogNewsletterTemplate($this->aIogNewsletterTemplate);
			}

			if ($this->aIogNewsletterLlista !== null) {
				if ($this->aIogNewsletterLlista->isModified() || $this->aIogNewsletterLlista->isNew()) {
					$affectedRows += $this->aIogNewsletterLlista->save($con);
				}
				$this->setIogNewsletterLlista($this->aIogNewsletterLlista);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = iogNewsletterPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = iogNewsletterPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += iogNewsletterPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->colliogNewsletterContents !== null) {
				foreach ($this->colliogNewsletterContents as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->colliogNewsletterImages !== null) {
				foreach ($this->colliogNewsletterImages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aIogNewsletterTemplate !== null) {
				if (!$this->aIogNewsletterTemplate->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aIogNewsletterTemplate->getValidationFailures());
				}
			}

			if ($this->aIogNewsletterLlista !== null) {
				if (!$this->aIogNewsletterLlista->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aIogNewsletterLlista->getValidationFailures());
				}
			}


			if (($retval = iogNewsletterPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->colliogNewsletterContents !== null) {
					foreach ($this->colliogNewsletterContents as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->colliogNewsletterImages !== null) {
					foreach ($this->colliogNewsletterImages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = iogNewsletterPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNumero();
				break;
			case 2:
				return $this->getDataPublicacio();
				break;
			case 3:
				return $this->getTitular();
				break;
			case 4:
				return $this->getTemplateId();
				break;
			case 5:
				return $this->getSendDate();
				break;
			case 6:
				return $this->getIogNewsletterLlistaId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = iogNewsletterPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNumero(),
			$keys[2] => $this->getDataPublicacio(),
			$keys[3] => $this->getTitular(),
			$keys[4] => $this->getTemplateId(),
			$keys[5] => $this->getSendDate(),
			$keys[6] => $this->getIogNewsletterLlistaId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = iogNewsletterPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNumero($value);
				break;
			case 2:
				$this->setDataPublicacio($value);
				break;
			case 3:
				$this->setTitular($value);
				break;
			case 4:
				$this->setTemplateId($value);
				break;
			case 5:
				$this->setSendDate($value);
				break;
			case 6:
				$this->setIogNewsletterLlistaId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = iogNewsletterPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNumero($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDataPublicacio($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitular($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTemplateId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSendDate($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIogNewsletterLlistaId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);

		if ($this->isColumnModified(iogNewsletterPeer::ID)) $criteria->add(iogNewsletterPeer::ID, $this->id);
		if ($this->isColumnModified(iogNewsletterPeer::NUMERO)) $criteria->add(iogNewsletterPeer::NUMERO, $this->numero);
		if ($this->isColumnModified(iogNewsletterPeer::DATA_PUBLICACIO)) $criteria->add(iogNewsletterPeer::DATA_PUBLICACIO, $this->data_publicacio);
		if ($this->isColumnModified(iogNewsletterPeer::TITULAR)) $criteria->add(iogNewsletterPeer::TITULAR, $this->titular);
		if ($this->isColumnModified(iogNewsletterPeer::TEMPLATE_ID)) $criteria->add(iogNewsletterPeer::TEMPLATE_ID, $this->template_id);
		if ($this->isColumnModified(iogNewsletterPeer::SEND_DATE)) $criteria->add(iogNewsletterPeer::SEND_DATE, $this->send_date);
		if ($this->isColumnModified(iogNewsletterPeer::IOG_NEWSLETTER_LLISTA_ID)) $criteria->add(iogNewsletterPeer::IOG_NEWSLETTER_LLISTA_ID, $this->iog_newsletter_llista_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);

		$criteria->add(iogNewsletterPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of iogNewsletter (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNumero($this->numero);

		$copyObj->setDataPublicacio($this->data_publicacio);

		$copyObj->setTitular($this->titular);

		$copyObj->setTemplateId($this->template_id);

		$copyObj->setSendDate($this->send_date);

		$copyObj->setIogNewsletterLlistaId($this->iog_newsletter_llista_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getiogNewsletterContents() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addiogNewsletterContent($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getiogNewsletterImages() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addiogNewsletterImage($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     iogNewsletter Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     iogNewsletterPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new iogNewsletterPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a IogNewsletterTemplate object.
	 *
	 * @param      IogNewsletterTemplate $v
	 * @return     iogNewsletter The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setIogNewsletterTemplate(IogNewsletterTemplate $v = null)
	{
		if ($v === null) {
			$this->setTemplateId(NULL);
		} else {
			$this->setTemplateId($v->getId());
		}

		$this->aIogNewsletterTemplate = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the IogNewsletterTemplate object, it will not be re-added.
		if ($v !== null) {
			$v->addiogNewsletter($this);
		}

		return $this;
	}


	/**
	 * Get the associated IogNewsletterTemplate object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     IogNewsletterTemplate The associated IogNewsletterTemplate object.
	 * @throws     PropelException
	 */
	public function getIogNewsletterTemplate(PropelPDO $con = null)
	{
		if ($this->aIogNewsletterTemplate === null && ($this->template_id !== null)) {
			$this->aIogNewsletterTemplate = IogNewsletterTemplatePeer::retrieveByPk($this->template_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aIogNewsletterTemplate->addiogNewsletters($this);
			 */
		}
		return $this->aIogNewsletterTemplate;
	}

	/**
	 * Declares an association between this object and a IogNewsletterLlista object.
	 *
	 * @param      IogNewsletterLlista $v
	 * @return     iogNewsletter The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setIogNewsletterLlista(IogNewsletterLlista $v = null)
	{
		if ($v === null) {
			$this->setIogNewsletterLlistaId(NULL);
		} else {
			$this->setIogNewsletterLlistaId($v->getId());
		}

		$this->aIogNewsletterLlista = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the IogNewsletterLlista object, it will not be re-added.
		if ($v !== null) {
			$v->addiogNewsletter($this);
		}

		return $this;
	}


	/**
	 * Get the associated IogNewsletterLlista object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     IogNewsletterLlista The associated IogNewsletterLlista object.
	 * @throws     PropelException
	 */
	public function getIogNewsletterLlista(PropelPDO $con = null)
	{
		if ($this->aIogNewsletterLlista === null && ($this->iog_newsletter_llista_id !== null)) {
			$this->aIogNewsletterLlista = IogNewsletterLlistaPeer::retrieveByPk($this->iog_newsletter_llista_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aIogNewsletterLlista->addiogNewsletters($this);
			 */
		}
		return $this->aIogNewsletterLlista;
	}

	/**
	 * Clears out the colliogNewsletterContents collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addiogNewsletterContents()
	 */
	public function cleariogNewsletterContents()
	{
		$this->colliogNewsletterContents = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the colliogNewsletterContents collection (array).
	 *
	 * By default this just sets the colliogNewsletterContents collection to an empty array (like clearcolliogNewsletterContents());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initiogNewsletterContents()
	{
		$this->colliogNewsletterContents = array();
	}

	/**
	 * Gets an array of iogNewsletterContent objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this iogNewsletter has previously been saved, it will retrieve
	 * related iogNewsletterContents from storage. If this iogNewsletter is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array iogNewsletterContent[]
	 * @throws     PropelException
	 */
	public function getiogNewsletterContents($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->colliogNewsletterContents === null) {
			if ($this->isNew()) {
			   $this->colliogNewsletterContents = array();
			} else {

				$criteria->add(iogNewsletterContentPeer::NEWSLETTER_ID, $this->id);

				iogNewsletterContentPeer::addSelectColumns($criteria);
				$this->colliogNewsletterContents = iogNewsletterContentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(iogNewsletterContentPeer::NEWSLETTER_ID, $this->id);

				iogNewsletterContentPeer::addSelectColumns($criteria);
				if (!isset($this->lastiogNewsletterContentCriteria) || !$this->lastiogNewsletterContentCriteria->equals($criteria)) {
					$this->colliogNewsletterContents = iogNewsletterContentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastiogNewsletterContentCriteria = $criteria;
		return $this->colliogNewsletterContents;
	}

	/**
	 * Returns the number of related iogNewsletterContent objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related iogNewsletterContent objects.
	 * @throws     PropelException
	 */
	public function countiogNewsletterContents(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->colliogNewsletterContents === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(iogNewsletterContentPeer::NEWSLETTER_ID, $this->id);

				$count = iogNewsletterContentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(iogNewsletterContentPeer::NEWSLETTER_ID, $this->id);

				if (!isset($this->lastiogNewsletterContentCriteria) || !$this->lastiogNewsletterContentCriteria->equals($criteria)) {
					$count = iogNewsletterContentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->colliogNewsletterContents);
				}
			} else {
				$count = count($this->colliogNewsletterContents);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a iogNewsletterContent object to this object
	 * through the iogNewsletterContent foreign key attribute.
	 *
	 * @param      iogNewsletterContent $l iogNewsletterContent
	 * @return     void
	 * @throws     PropelException
	 */
	public function addiogNewsletterContent(iogNewsletterContent $l)
	{
		if ($this->colliogNewsletterContents === null) {
			$this->initiogNewsletterContents();
		}
		if (!in_array($l, $this->colliogNewsletterContents, true)) { // only add it if the **same** object is not already associated
			array_push($this->colliogNewsletterContents, $l);
			$l->setiogNewsletter($this);
		}
	}

	/**
	 * Clears out the colliogNewsletterImages collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addiogNewsletterImages()
	 */
	public function cleariogNewsletterImages()
	{
		$this->colliogNewsletterImages = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the colliogNewsletterImages collection (array).
	 *
	 * By default this just sets the colliogNewsletterImages collection to an empty array (like clearcolliogNewsletterImages());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initiogNewsletterImages()
	{
		$this->colliogNewsletterImages = array();
	}

	/**
	 * Gets an array of iogNewsletterImage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this iogNewsletter has previously been saved, it will retrieve
	 * related iogNewsletterImages from storage. If this iogNewsletter is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array iogNewsletterImage[]
	 * @throws     PropelException
	 */
	public function getiogNewsletterImages($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->colliogNewsletterImages === null) {
			if ($this->isNew()) {
			   $this->colliogNewsletterImages = array();
			} else {

				$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

				iogNewsletterImagePeer::addSelectColumns($criteria);
				$this->colliogNewsletterImages = iogNewsletterImagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

				iogNewsletterImagePeer::addSelectColumns($criteria);
				if (!isset($this->lastiogNewsletterImageCriteria) || !$this->lastiogNewsletterImageCriteria->equals($criteria)) {
					$this->colliogNewsletterImages = iogNewsletterImagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastiogNewsletterImageCriteria = $criteria;
		return $this->colliogNewsletterImages;
	}

	/**
	 * Returns the number of related iogNewsletterImage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related iogNewsletterImage objects.
	 * @throws     PropelException
	 */
	public function countiogNewsletterImages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->colliogNewsletterImages === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

				$count = iogNewsletterImagePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

				if (!isset($this->lastiogNewsletterImageCriteria) || !$this->lastiogNewsletterImageCriteria->equals($criteria)) {
					$count = iogNewsletterImagePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->colliogNewsletterImages);
				}
			} else {
				$count = count($this->colliogNewsletterImages);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a iogNewsletterImage object to this object
	 * through the iogNewsletterImage foreign key attribute.
	 *
	 * @param      iogNewsletterImage $l iogNewsletterImage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addiogNewsletterImage(iogNewsletterImage $l)
	{
		if ($this->colliogNewsletterImages === null) {
			$this->initiogNewsletterImages();
		}
		if (!in_array($l, $this->colliogNewsletterImages, true)) { // only add it if the **same** object is not already associated
			array_push($this->colliogNewsletterImages, $l);
			$l->setiogNewsletter($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this iogNewsletter is new, it will return
	 * an empty collection; or if this iogNewsletter has previously
	 * been saved, it will retrieve related iogNewsletterImages from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in iogNewsletter.
	 */
	public function getiogNewsletterImagesJoinsfAsset($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(iogNewsletterPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->colliogNewsletterImages === null) {
			if ($this->isNew()) {
				$this->colliogNewsletterImages = array();
			} else {

				$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

				$this->colliogNewsletterImages = iogNewsletterImagePeer::doSelectJoinsfAsset($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(iogNewsletterImagePeer::IOG_NEWSLETTER_ID, $this->id);

			if (!isset($this->lastiogNewsletterImageCriteria) || !$this->lastiogNewsletterImageCriteria->equals($criteria)) {
				$this->colliogNewsletterImages = iogNewsletterImagePeer::doSelectJoinsfAsset($criteria, $con, $join_behavior);
			}
		}
		$this->lastiogNewsletterImageCriteria = $criteria;

		return $this->colliogNewsletterImages;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->colliogNewsletterContents) {
				foreach ((array) $this->colliogNewsletterContents as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->colliogNewsletterImages) {
				foreach ((array) $this->colliogNewsletterImages as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->colliogNewsletterContents = null;
		$this->colliogNewsletterImages = null;
			$this->aIogNewsletterTemplate = null;
			$this->aIogNewsletterLlista = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseiogNewsletter:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseiogNewsletter::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseiogNewsletter
