generator:
  class: sfPropelGenerator
  param:
    model_class:           iogNewsletterTemplate
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              iogNewsletterTemplate
    plural:                iogNewsletterTemplates
    route_prefix:          iog_newsletter_template_iogNewsletterTemplate
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
