<?php


/**
 * Skeleton subclass for representing a row from the 'iog_newsletter_template' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec  8 08:09:07 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.iogNewsletterPlugin.lib.model
 */
class IogNewsletterTemplate extends BaseIogNewsletterTemplate {
  public function __toString()
  {
    return $this->getName();
  }

} // IogNewsletterTemplate
