<?php


/**
 * Skeleton subclass for representing a row from the 'iog_newsletter_emails' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec  9 07:05:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.iogNewsletterPlugin.lib.model
 */
class IogNewsletterEmails extends BaseIogNewsletterEmails {

} // IogNewsletterEmails
