<?php


/**
 * Skeleton subclass for representing a row from the 'iog_newsletter_template_apartat' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Dec 31 15:27:19 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.iogNewsletterPlugin.lib.model
 */
class IogNewsletterTemplateApartat extends BaseIogNewsletterTemplateApartat {

} // IogNewsletterTemplateApartat
