<?php


/**
 * Skeleton subclass for performing query and update operations on the 'iog_newsletter_llista' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec 30 09:41:15 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.iogNewsletterPlugin.lib.model
 */
class IogNewsletterLlistaPeer extends BaseIogNewsletterLlistaPeer {

} // IogNewsletterLlistaPeer
