<?php

/**
 * Skeleton subclass for performing query and update operations on the 'iog_newsletter_emails' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec  9 07:05:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.iogNewsletterPlugin.lib.model
 */
class IogNewsletterEmailsPeer extends BaseIogNewsletterEmailsPeer {
/**
 * Return an array with a pair email => nom & cognoms
 * 
 * @param String $culture
 * @return array 
 */
  public static function doSelectByLlista($llista_id) {
    $c = new Criteria();
    $c->add(self::IOG_NEWSLETTER_LLISTA_ID, $llista_id);
    $rs = self::doSelectStmt($c);
$arr = array();
    while ($r = $rs->fetch(PDO::FETCH_ASSOC))
    {
      $arr[$r['EMAIL']] = $r['NOM'] . ' ' . $r['COGNOMS'];

    }
    return $arr;
  }

}

// IogNewsletterEmailsPeer
